var n;n||=typeof Immolate != 'undefined' ? Immolate : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",da=(a,b)=>{throw b;},ea=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ea=__filename:ba&&(ea=self.location.href);var p="",fa,q;
if(ca){var fs=require("node:fs");p=__dirname+"/";q=a=>{a=r(a)?new URL(a):a;return fs.readFileSync(a)};fa=async a=>{a=r(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);typeof module!="undefined"&&(module.exports=n);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{p=(new URL(".",ea)).href}catch{}ba&&(q=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});fa=async a=>{if(r(a))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var z=console.error.bind(console),ha=!1,r=a=>a.startsWith("file://");
function ia(){var a=n.preRun;a&&(typeof a=="function"&&(a=[a]),ja.push(...a));for(a=ja;a.length>0;)a.shift()(n)}function ka(){var a=n.postRun;a&&(typeof a=="function"&&(a=[a]),la.push(...a));for(a=la;a.length>0;)a.shift()(n)}function A(a){n.onAbort?.(a);a=`Aborted(${a})`;z(a);ha=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ma;
async function na(a){try{var b=await fa(a);return new Uint8Array(b)}catch{}if(q)a=q(a);else throw"both async and sync fetching of the wasm failed";return a}async function oa(a,b){try{var c=await na(a);return await WebAssembly.instantiate(c,b)}catch(d){z(`failed to asynchronously prepare wasm: ${d}`),A(d)}}
async function pa(a){var b=ma;if(!r(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){z(`wasm streaming compile failed: ${d}`),z("falling back to ArrayBuffer instantiation")}return oa(b,a)}class qa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var la=[],ja=[],ra=!0,sa,B;class ta{constructor(a){this.H=a-24}init(a,b){B[this.H+16>>2]=0;B[this.H+4>>2]=a;B[this.H+8>>2]=b}}
var va=0,C,E=a=>{for(var b="";;){var c=C[a++];if(!c)return b;b+=String.fromCharCode(c)}},F={},I={},J={};class K extends Error{constructor(a){super(a);this.name="BindingError"}}var wa=a=>{throw new K(a);};function xa(a,b,c={}){var d=b.name;if(!a)throw new K(`type "${d}" must have a positive integer typeid pointer`);if(I.hasOwnProperty(a)){if(c.ka)return;throw new K(`Cannot register type '${d}' twice`);}I[a]=b;delete J[a];F.hasOwnProperty(a)&&(b=F[a],delete F[a],b.forEach(e=>e()))}
function L(a,b,c={}){return xa(a,b,c)}
var M,N,O,ya,za,Aa=(a,b,c)=>{switch(b){case 1:return c?d=>sa[d]:d=>C[d];case 2:return c?d=>M[d>>1]:d=>N[d>>1];case 4:return c?d=>O[d>>2]:d=>B[d>>2];case 8:return c?d=>ya[d>>3]:d=>za[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ba=a=>{throw new K(a.F.I.G.name+" instance already deleted");},Ca=!1,Da=()=>{},P=a=>{if(!globalThis.FinalizationRegistry)return P=b=>b,a;Ca=new FinalizationRegistry(b=>{b=b.F;--b.count.value;0===b.count.value&&(b.L?b.O.T(b.L):b.I.G.T(b.H))});P=
b=>{var c=b.F;c.L&&Ca.register(b,{F:c},b);return b};Da=b=>{Ca.unregister(b)};return P(a)},Ea=[];function Q(){}
var Fa=(a,b)=>Object.defineProperty(b,"name",{value:a}),Ga={},Ha=(a,b,c)=>{if(void 0===a[b].K){var d=a[b];a[b]=function(...e){if(!a[b].K.hasOwnProperty(e.length))throw new K(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].K})!`);return a[b].K[e.length].apply(this,e)};a[b].K=[];a[b].K[d.V]=d}},Ia=(a,b,c)=>{if(n.hasOwnProperty(a)){if(void 0===c||void 0!==n[a].K&&void 0!==n[a].K[c])throw new K(`Cannot register public name '${a}' twice`);Ha(n,a,a);if(n[a].K.hasOwnProperty(c))throw new K(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
n[a].K[c]=b}else n[a]=b,n[a].V=c},Ja=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return b>=48&&b<=57?`_${a}`:a};function Ka(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.R=c;this.T=d;this.M=e;this.ia=f;this.Y=g;this.ha=h;this.ma=[]}
var R=(a,b,c)=>{for(;b!==c;){if(!b.Y)throw new K(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Y(a);b=b.M}return a},La=a=>{if(a===null)return"null";var b=typeof a;return b==="object"||b==="array"||b==="function"?a.toString():""+a};
function Ma(a,b){if(b===null){if(this.aa)throw new K(`null is not a valid ${this.name}`);return 0}if(!b.F)throw new K(`Cannot pass "${La(b)}" as a ${this.name}`);if(!b.F.H)throw new K(`Cannot pass deleted object as a pointer of type ${this.name}`);return R(b.F.H,b.F.I.G,this.G)}
function Na(a,b){if(b===null){if(this.aa)throw new K(`null is not a valid ${this.name}`);if(this.$){var c=this.na();a!==null&&a.push(this.T,c);return c}return 0}if(!b||!b.F)throw new K(`Cannot pass "${La(b)}" as a ${this.name}`);if(!b.F.H)throw new K(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Z&&b.F.I.Z)throw new K(`Cannot convert argument of type ${b.F.O?b.F.O.name:b.F.I.name} to parameter type ${this.name}`);c=R(b.F.H,b.F.I.G,this.G);if(this.$){if(void 0===b.F.L)throw new K("Passing raw pointer to smart pointer is illegal");
switch(this.pa){case 0:if(b.F.O===this)c=b.F.L;else throw new K(`Cannot convert argument of type ${b.F.O?b.F.O.name:b.F.I.name} to parameter type ${this.name}`);break;case 1:c=b.F.L;break;case 2:if(b.F.O===this)c=b.F.L;else{var d=b.clone();c=this.oa(c,Oa(()=>d["delete"]()));a!==null&&a.push(this.T,c)}break;default:throw new K("Unsupported sharing policy");}}return c}
function Pa(a,b){if(b===null){if(this.aa)throw new K(`null is not a valid ${this.name}`);return 0}if(!b.F)throw new K(`Cannot pass "${La(b)}" as a ${this.name}`);if(!b.F.H)throw new K(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.F.I.Z)throw new K(`Cannot convert argument of type ${b.F.I.name} to parameter type ${this.name}`);return R(b.F.H,b.F.I.G,this.G)}function S(a){return this.J(B[a>>2])}
var Qa=(a,b,c)=>{if(b===c)return a;if(void 0===c.M)return null;a=Qa(a,b,c.M);return a===null?null:c.ha(a)},Ra={},Sa=(a,b)=>{if(b===void 0)throw new K("ptr should not be undefined");for(;a.M;)b=a.Y(b),a=a.M;return Ra[b]};class T extends Error{constructor(a){super(a);this.name="InternalError"}}
var Ta=(a,b)=>{if(!b.I||!b.H)throw new T("makeClassHandle requires ptr and ptrType");if(!!b.O!==!!b.L)throw new T("Both smartPtrType and smartPtr must be specified");b.count={value:1};return P(Object.create(a,{F:{value:b,writable:!0}}))};function Ua(a,b,c,d,e,f,g,h,k,m,l){this.name=a;this.G=b;this.aa=c;this.Z=d;this.$=e;this.la=f;this.pa=g;this.fa=h;this.na=k;this.oa=m;this.T=l;e||b.M!==void 0?this.N=Na:(this.N=d?Ma:Pa,this.P=null)}
var Va=(a,b,c)=>{if(!n.hasOwnProperty(a))throw new T("Replacing nonexistent public symbol");void 0!==n[a].K&&void 0!==c?n[a].K[c]=b:(n[a]=b,n[a].V=c)},Wa=[],U=(a,b)=>{a=E(a);var c;(c=Wa[b])||(Wa[b]=c=Xa.get(b));if(typeof c!="function")throw new K(`unknown function pointer with signature ${a}: ${b}`);return c};class Ya extends Error{}
var $a=a=>{a=Za(a);var b=E(a);V(a);return b},W=(a,b)=>{function c(f){e[f]||I[f]||(J[f]?J[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ya(`${a}: `+d.map($a).join([", "]));},X=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new T("Mismatched type converter count");for(var k=0;k<a.length;++k)L(a[k],h[k])}a.forEach(h=>J[h]=b);var e=Array(b.length),f=[],g=0;for(let [h,k]of b.entries())I.hasOwnProperty(k)?e[h]=I[k]:(f.push(k),F.hasOwnProperty(k)||(F[k]=[]),F[k].push(()=>
{e[h]=I[k];++g;g===f.length&&d(e)}));0===f.length&&d(e)},ab=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(B[b+d*4>>2]);return c},cb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function db(a){for(var b=1;b<a.length;++b)if(a[b]!==null&&a[b].P===void 0)return!0;return!1}
function eb(a,b,c,d,e,f){var g=b.length;if(g<2)throw new K("argTypes array size mismatch! Must at least get return value and receiver (this) types!");var h=b[1]!==null&&c!==null,k=db(b);c=!b[0].ea;var m=b[0],l=b[1];d=[a,wa,d,e,cb,m.J.bind(m),l?.N.bind(l)];for(e=2;e<g;++e)m=b[e],d.push(m.N.bind(m));if(!k)for(e=h?1:2;e<b.length;++e)b[e].P!==null&&d.push(b[e].P);k=db(b);e=b.length-2;l=[];m=["fn"];h&&m.push("thisWired");for(g=0;g<e;++g)l.push(`arg${g}`),m.push(`arg${g}Wired`);l=l.join();m=m.join();l=
`return function (${l}) {\n`;k&&(l+="var destructors = [];\n");var u=k?"destructors":"null",w="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(l+=`var thisWired = toClassParamWire(${u}, this);\n`);for(g=0;g<e;++g){var t=`toArg${g}Wire`;l+=`var arg${g}Wired = ${t}(${u}, arg${g});\n`;w.push(t)}l+=(c||f?"var rv = ":"")+`invoker(${m});\n`;if(k)l+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=g===1?"thisWired":`arg${g-2}Wired`,b[g].P!==
null&&(l+=`${f}_dtor(${f});\n`,w.push(`${f}_dtor`));c&&(l+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(w,l+"}\n"))(...d);return Fa(a,b)}
var fb=a=>{a=a.trim();var b=a.indexOf("(");return b===-1?a:a.slice(0,b)},gb=(a,b,c)=>{if(!(a instanceof Object))throw new K(`${c} with invalid "this": ${a}`);if(!(a instanceof b.G.constructor))throw new K(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.F.H)throw new K(`cannot call emscripten binding method ${c} on deleted object`);return R(a.F.H,a.F.I.G,b.G)},hb=[],Y=[0,1,,1,null,1,!0,1,!1,1],ib=a=>{a>9&&0===--Y[a+1]&&(Y[a]=void 0,hb.push(a))},jb=a=>{if(!a)throw new K(`Cannot use deleted val. handle = ${a}`);
return Y[a]},Oa=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:let b=hb.pop()||Y.length;Y[b]=a;Y[b+1]=1;return b}},kb={name:"emscripten::val",J:a=>{var b=jb(a);ib(a);return b},N:(a,b)=>Oa(b),S,P:null},lb,mb,nb=(a,b)=>{switch(b){case 4:return function(c){return this.J(lb[c>>2])};case 8:return function(c){return this.J(mb[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},ob=(a,b,c)=>{var d=(e,f)=>{var g=0;return{next(){if(g>=
e)return{done:!0};var h=g;g++;return{value:f(h),done:!1}},[Symbol.iterator](){return this}}};a[Symbol.iterator]||(a[Symbol.iterator]=function(){var e=this[b]();return d(e,f=>this[c](f))})},pb=Object.assign({optional:!0},kb),qb=globalThis.TextDecoder&&new TextDecoder,rb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},sb=(a=0,b)=>{var c=C;b=rb(c,a,b,!0);if(b-a>16&&c.buffer&&qb)return qb.decode(c.subarray(a,b));for(var d="";a<b;){var e=c[a++];if(e&128){var f=c[a++]&63;if((e&224)==192)d+=
String.fromCharCode((e&31)<<6|f);else{var g=c[a++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|c[a++]&63;e<65536?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},tb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,ub=(a,b,c)=>{a>>=1;b=rb(N,a,b/2,c);if(b-a>16&&tb)return tb.decode(N.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(N[a]);return c},vb=(a,b,c=2147483647)=>{if(c<2)return 0;c-=2;var d=
b;c=c<a.length*2?c/2:a.length;for(var e=0;e<c;++e)M[b>>1]=a.charCodeAt(e),b+=2;M[b>>1]=0;return b-d},wb=a=>a.length*2,xb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=B[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},yb=(a,b,c=2147483647)=>{if(c<4)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);f>65535&&e++;O[b>>2]=f;b+=4;if(b+4>c)break}O[b>>2]=0;return b-d},zb=a=>{for(var b=0,c=0;c<a.length;++c)a.codePointAt(c)>65535&&c++,b+=4;return b},Ab=[],Bb=
a=>{var b=Ab.length;Ab.push(a);return b},Cb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=B[b+d*4>>2],g=I[f];if(void 0===g)throw a=`${`parameter ${d}`} has unknown type ${$a(f)}`,new K(a);c[e]=g}return c},Db=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(B[b>>2]=Oa(d));return a},Eb={},Fb=a=>{var b=Eb[a];return b===void 0?E(a):b};
(()=>{var a=Q.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Q&&c instanceof Q))return!1;var d=this.F.I.G,e=this.F.H;c.F=c.F;var f=c.F.I.G;for(c=c.F.H;d.M;)e=d.Y(e),d=d.M;for(;f.M;)c=f.Y(c),f=f.M;return d===f&&e===c},clone:function(){this.F.H||Ba(this);if(this.F.X)return this.F.count.value+=1,this;var c=P,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.F;c=c(e.call(d,f,{F:{value:{count:g.count,W:g.W,X:g.X,H:g.H,I:g.I,L:g.L,O:g.O}}}));c.F.count.value+=1;c.F.W=!1;return c},
["delete"](){this.F.H||Ba(this);if(this.F.W&&!this.F.X)throw new K("Object already scheduled for deletion");Da(this);var c=this.F;--c.count.value;0===c.count.value&&(c.L?c.O.T(c.L):c.I.G.T(c.H));this.F.X||(this.F.L=void 0,this.F.H=void 0)},isDeleted:function(){return!this.F.H},deleteLater:function(){this.F.H||Ba(this);if(this.F.W&&!this.F.X)throw new K("Object already scheduled for deletion");Ea.push(this);this.F.W=!0;return this}});var b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(Ua.prototype,{ja(a){this.fa&&(a=this.fa(a));return a},da(a){this.T?.(a)},S,J:function(a){function b(){return this.$?Ta(this.G.R,{I:this.la,H:c,O:this,L:a}):Ta(this.G.R,{I:this,H:a})}var c=this.ja(a);if(!c)return this.da(a),null;var d=Sa(this.G,c);if(void 0!==d){if(0===d.F.count.value)return d.F.H=c,d.F.L=a,d.clone();d=d.clone();this.da(a);return d}d=this.G.ia(c);d=Ga[d];if(!d)return b.call(this);d=this.Z?d.ga:d.pointerType;var e=Qa(c,this.G,d.G);return e===null?b.call(this):this.$?Ta(d.G.R,
{I:d,H:e,O:this,L:a}):Ta(d.G.R,{I:d,H:e})}});n.noExitRuntime&&(ra=n.noExitRuntime);n.printErr&&(z=n.printErr);var Z=n.preInit;if(Z)for(typeof Z=="function"&&(n.preInit=Z=[Z]);Z.length>0;)Z.shift()();
var Za,Gb,Hb,V,Ib,Xa,Jb={m:(a,b,c)=>{(new ta(a)).init(b,c);va++;A()},r:()=>A(""),p:(a,b,c,d,e)=>{b=E(b);d=d===0n;var f=g=>g;if(d){let g=c*8;f=h=>BigInt.asUintN(g,h);e=f(e)}L(a,{name:b,J:f,N:(g,h)=>{typeof h=="number"&&(h=BigInt(h));return h},S:Aa(b,c,!d),P:null})},v:(a,b,c,d)=>{b=E(b);L(a,{name:b,J:function(e){return!!e},N:function(e,f){return f?c:d},S:function(e){return this.J(C[e])},P:null})},e:(a,b,c,d,e,f,g,h,k,m,l,u,w)=>{l=E(l);f=U(e,f);h&&=U(g,h);m&&=U(k,m);w=U(u,w);var t=Ja(l);Ia(t,function(){W(`Cannot construct ${l} due to unbound types`,
[d])});X([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var x=v.G;var G=x.R}else G=Q.prototype;v=Fa(l,function(...ua){if(Object.getPrototypeOf(this)!==H)throw new K(`Use 'new' to construct ${l}`);if(void 0===y.U)throw new K(`${l} has no accessible constructor`);var bb=y.U[ua.length];if(void 0===bb)throw new K(`Tried to invoke ctor of ${l} with invalid number of parameters (${ua.length}) - expected (${Object.keys(y.U).toString()}) parameters instead!`);return bb.apply(this,ua)});var H=Object.create(G,{constructor:{value:v}});
v.prototype=H;var y=new Ka(l,v,H,w,x,f,h,m);if(y.M){var D;(D=y.M).ba??(D.ba=[]);y.M.ba.push(y)}x=new Ua(l,y,!0,!1,!1);D=new Ua(l+"*",y,!1,!1,!1);G=new Ua(l+" const*",y,!1,!0,!1);Ga[a]={pointerType:D,ga:G};Va(t,v);return[x,D,G]})},c:(a,b,c,d,e,f)=>{var g=ab(b,c);e=U(d,e);X([],[a],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.G.U&&(h.G.U=[]);if(void 0!==h.G.U[b-1])throw new K(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
h.G.U[b-1]=()=>{W(`Cannot construct ${h.name} due to unbound types`,g)};X([],g,m=>{m.splice(1,0,null);h.G.U[b-1]=eb(k,m,null,e,f);return[]});return[]})},a:(a,b,c,d,e,f,g,h,k)=>{var m=ab(c,d);b=E(b);b=fb(b);f=U(e,f);X([],[a],l=>{function u(){W(`Cannot call ${w} due to unbound types`,m)}l=l[0];var w=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&l.G.ma.push(b);var t=l.G.R,v=t[b];void 0===v||void 0===v.K&&v.className!==l.name&&v.V===c-2?(u.V=c-2,u.className=l.name,t[b]=u):(Ha(t,b,
w),t[b].K[c-2]=u);X([],m,x=>{x=eb(w,x,l,f,g,k);void 0===t[b].K?(x.V=c-2,t[b]=x):t[b].K[c-2]=x;return[]});return[]})},b:(a,b,c,d,e,f,g,h,k,m)=>{b=E(b);e=U(d,e);X([],[a],l=>{l=l[0];var u=`${l.name}.${b}`,w={get(){W(`Cannot access ${u} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};w.set=k?()=>W(`Cannot access ${u} due to unbound types`,[c,g]):()=>{throw new K(u+" is a read-only property");};Object.defineProperty(l.G.R,b,w);X([],k?[c,g]:[c],t=>{var v=t[0],x={get(){var H=gb(this,l,u+" getter");
return v.J(e(f,H))},enumerable:!0};if(k){k=U(h,k);var G=t[1];x.set=function(H){var y=gb(this,l,u+" setter"),D=[];k(m,y,G.N(D,H));cb(D)}}Object.defineProperty(l.G.R,b,x);return[]});return[]})},q:(a,b,c)=>{a=E(a);X([],[b],d=>{d=d[0];n[a]=d.J(c);return[]})},t:a=>L(a,kb),o:(a,b,c)=>{b=E(b);L(a,{name:b,J:d=>d,N:(d,e)=>e,S:nb(b,c),P:null})},n:(a,b,c,d,e,f,g)=>{var h=ab(b,c);a=E(a);a=fb(a);e=U(d,e);Ia(a,function(){W(`Cannot call ${a} due to unbound types`,h)},b-1);X([],h,k=>{k=[k[0],null].concat(k.slice(1));
Va(a,eb(a,k,null,e,f,g),b-1);return[]})},f:(a,b,c,d,e)=>{b=E(b);var f=h=>h;if(d===0){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}L(a,{name:b,J:f,N:(h,k)=>k,S:Aa(b,c,d!==0),P:null})},h:(a,b,c,d)=>{c=E(c);d=E(d);X([],[a,b],e=>{ob(e[0].G.R,c,d);return[]})},d:(a,b,c)=>{function d(f){return new e(sa.buffer,B[f+4>>2],B[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=E(c);L(a,{name:c,J:d,S:d},{ka:!0})},i:a=>{L(a,pb)},u:(a,
b)=>{b=E(b);L(a,{name:b,J(c){var d=(d=c+4)?sb(d,B[c>>2]):"";V(c);return d},N(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f=typeof d=="string";if(!(f||ArrayBuffer.isView(d)&&d.BYTES_PER_ELEMENT==1))throw new K("Cannot pass non-string to std::string");var g;if(f)for(e=g=0;e<d.length;++e){var h=d.charCodeAt(e);h<=127?g++:h<=2047?g+=2:h>=55296&&h<=57343?(g+=4,++e):g+=3}else g=d.length;e=g;g=Gb(4+e+1);h=g+4;B[g>>2]=e;if(f){if(f=h,h=e+1,e=C,h>0){h=f+h-1;for(var k=0;k<d.length;++k){var m=
d.codePointAt(k);if(m<=127){if(f>=h)break;e[f++]=m}else if(m<=2047){if(f+1>=h)break;e[f++]=192|m>>6;e[f++]=128|m&63}else if(m<=65535){if(f+2>=h)break;e[f++]=224|m>>12;e[f++]=128|m>>6&63;e[f++]=128|m&63}else{if(f+3>=h)break;e[f++]=240|m>>18;e[f++]=128|m>>12&63;e[f++]=128|m>>6&63;e[f++]=128|m&63;k++}}e[f]=0}}else C.set(d,h);c!==null&&c.push(V,g);return g},S,P(c){V(c)}})},j:(a,b,c)=>{c=E(c);if(b===2){var d=ub;var e=vb;var f=wb}else d=xb,e=yb,f=zb;L(a,{name:c,J:g=>{var h=d(g+4,B[g>>2]*b,!0);V(g);return h},
N:(g,h)=>{if(typeof h!="string")throw new K(`Cannot pass non-string to C++ string type ${c}`);var k=f(h),m=Gb(4+k+b);B[m>>2]=k/b;e(h,m+4,k+b);g!==null&&g.push(V,m);return m},S,P(g){V(g)}})},w:(a,b)=>{b=E(b);L(a,{ea:!0,name:b,J:()=>{},N:()=>{}})},g:(a,b,c)=>{var d;[b,...d]=Cb(a,b);var e=b.N.bind(b),f=d.map(k=>k.S.bind(k));a--;var g={toValue:jb};a=f.map((k,m)=>{var l=`argFromPtr${m}`;g[l]=k;return`${l}(args${m?"+"+m*8:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";
break;case 3:h="";break;case 1:g.getStringOrSymbol=Fb,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;b.ea||(g.toReturnWire=e,g.emval_returnValue=Db,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n${h}\n}`;c=(new Function(Object.keys(g),h))(...Object.values(g));b=`methodCaller<(${d.map(k=>k.name)}) => ${b.name}>`;return Bb(Fa(b,c))},l:(a,b,c,d,e)=>Ab[a](b,c,d,e),k:a=>{var b=jb(a);cb(b);ib(a)},s:()=>{A("OOM")}};
function Kb(){var a=Hb;try{var b=a(0,0);ra||(n.onExit?.(b),ha=!0);da(b,new qa(b))}catch(c){c instanceof qa||c=="unwind"||da(1,c)}}async function Lb(){ia();var a=n.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));ha||(Mb.y(),n.onRuntimeInitialized?.(),n.noInitialRun||Kb(),ka())}var Mb;
(async function(){function a(d){d=Mb=d.exports;Za=d.z;Gb=d.B;Hb=n._main=d.C;V=d.D;Ib=d.x;Xa=d.A;d=Ib.buffer;sa=new Int8Array(d);M=new Int16Array(d);C=new Uint8Array(d);N=new Uint16Array(d);O=new Int32Array(d);B=new Uint32Array(d);lb=new Float32Array(d);mb=new Float64Array(d);ya=new BigInt64Array(d);za=new BigUint64Array(d);return Mb}var b={a:Jb},c=n.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});ma??=n.locateFile?n.locateFile("immolate.wasm",p):p+"immolate.wasm";return function(d){return a(d.instance)}(await pa(b))})().then(()=>
Lb());
